//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::Ossify.Bindings.Specific.TMP.TextToFloatVariableBinder.FloatEvent))]
	public class PropertyProvider_Ossify_Bindings_Specific_TMP_TextToFloatVariableBinder_FloatEvent : Unity.VisualScripting.SerializedPropertyProvider<Ossify.Bindings.Specific.TMP.TextToFloatVariableBinder.FloatEvent>
	{
	}
}
